# Generated by Django 5.1.3 on 2024-11-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='apt_num',
        ),
        migrations.AlterField(
            model_name='votes',
            name='precinct_num',
            field=models.TextField(),
        ),
    ]
