# Generated by Django 5.1.3 on 2024-11-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_remove_votes_apt_num_alter_votes_precinct_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='party_affiliation',
            field=models.TextField(),
        ),
    ]
