# Generated by Django 5.1.3 on 2024-11-14 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('profile_img', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('Goal', models.IntegerField()),
                ('waterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('amount_consumed', models.FloatField()),
                ('wprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterlog.wprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('wprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterlog.wprofile')),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('wprofile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wprofile1', to='waterlog.wprofile')),
                ('wprofile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wprofile2', to='waterlog.wprofile')),
            ],
        ),
    ]
