# Generated by Django 5.1.3 on 2024-11-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlog',
            name='water_type',
            field=models.CharField(choices=[('Cup', 'Cup'), ('Bottle', 'Bottle'), ('Others', 'Others')], default='Plain', max_length=50),
        ),
    ]
