# Generated by Django 5.1.2 on 2024-10-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
